// Generated by gencpp from file serverAclient/addints.msg
// DO NOT EDIT!


#ifndef SERVERACLIENT_MESSAGE_ADDINTS_H
#define SERVERACLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <serverAclient/addintsRequest.h>
#include <serverAclient/addintsResponse.h>


namespace serverAclient
{

struct addints
{

typedef addintsRequest Request;
typedef addintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addints
} // namespace serverAclient


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serverAclient::addints > {
  static const char* value()
  {
    return "38486e151d36f54c3341e517d9e88650";
  }

  static const char* value(const ::serverAclient::addints&) { return value(); }
};

template<>
struct DataType< ::serverAclient::addints > {
  static const char* value()
  {
    return "serverAclient/addints";
  }

  static const char* value(const ::serverAclient::addints&) { return value(); }
};


// service_traits::MD5Sum< ::serverAclient::addintsRequest> should match
// service_traits::MD5Sum< ::serverAclient::addints >
template<>
struct MD5Sum< ::serverAclient::addintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serverAclient::addints >::value();
  }
  static const char* value(const ::serverAclient::addintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverAclient::addintsRequest> should match
// service_traits::DataType< ::serverAclient::addints >
template<>
struct DataType< ::serverAclient::addintsRequest>
{
  static const char* value()
  {
    return DataType< ::serverAclient::addints >::value();
  }
  static const char* value(const ::serverAclient::addintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serverAclient::addintsResponse> should match
// service_traits::MD5Sum< ::serverAclient::addints >
template<>
struct MD5Sum< ::serverAclient::addintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serverAclient::addints >::value();
  }
  static const char* value(const ::serverAclient::addintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serverAclient::addintsResponse> should match
// service_traits::DataType< ::serverAclient::addints >
template<>
struct DataType< ::serverAclient::addintsResponse>
{
  static const char* value()
  {
    return DataType< ::serverAclient::addints >::value();
  }
  static const char* value(const ::serverAclient::addintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVERACLIENT_MESSAGE_ADDINTS_H
