// Generated by gencpp from file serverAclient/addintsResponse.msg
// DO NOT EDIT!


#ifndef SERVERACLIENT_MESSAGE_ADDINTSRESPONSE_H
#define SERVERACLIENT_MESSAGE_ADDINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serverAclient
{
template <class ContainerAllocator>
struct addintsResponse_
{
  typedef addintsResponse_<ContainerAllocator> Type;

  addintsResponse_()
    : res(0)  {
    }
  addintsResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::serverAclient::addintsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serverAclient::addintsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addintsResponse_

typedef ::serverAclient::addintsResponse_<std::allocator<void> > addintsResponse;

typedef boost::shared_ptr< ::serverAclient::addintsResponse > addintsResponsePtr;
typedef boost::shared_ptr< ::serverAclient::addintsResponse const> addintsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serverAclient::addintsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serverAclient::addintsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serverAclient::addintsResponse_<ContainerAllocator1> & lhs, const ::serverAclient::addintsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serverAclient::addintsResponse_<ContainerAllocator1> & lhs, const ::serverAclient::addintsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serverAclient

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serverAclient::addintsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serverAclient::addintsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serverAclient::addintsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serverAclient::addintsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serverAclient::addintsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serverAclient::addintsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serverAclient::addintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::serverAclient::addintsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca16cfbd5443ad97ULL;
  static const uint64_t static_value2 = 0xf6cc7ffd6bb67292ULL;
};

template<class ContainerAllocator>
struct DataType< ::serverAclient::addintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serverAclient/addintsResponse";
  }

  static const char* value(const ::serverAclient::addintsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serverAclient::addintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 res\n"
;
  }

  static const char* value(const ::serverAclient::addintsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serverAclient::addintsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addintsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serverAclient::addintsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serverAclient::addintsResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVERACLIENT_MESSAGE_ADDINTSRESPONSE_H
