// Generated by gencpp from file pubAsub/info.msg
// DO NOT EDIT!


#ifndef PUBASUB_MESSAGE_INFO_H
#define PUBASUB_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pubAsub
{
template <class ContainerAllocator>
struct info_
{
  typedef info_<ContainerAllocator> Type;

  info_()
    : name()
    , count(0)
    , information(0.0)  {
    }
  info_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , count(0)
    , information(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _count_type;
  _count_type count;

   typedef float _information_type;
  _information_type information;





  typedef boost::shared_ptr< ::pubAsub::info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pubAsub::info_<ContainerAllocator> const> ConstPtr;

}; // struct info_

typedef ::pubAsub::info_<std::allocator<void> > info;

typedef boost::shared_ptr< ::pubAsub::info > infoPtr;
typedef boost::shared_ptr< ::pubAsub::info const> infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pubAsub::info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pubAsub::info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pubAsub::info_<ContainerAllocator1> & lhs, const ::pubAsub::info_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.count == rhs.count &&
    lhs.information == rhs.information;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pubAsub::info_<ContainerAllocator1> & lhs, const ::pubAsub::info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pubAsub

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pubAsub::info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pubAsub::info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pubAsub::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pubAsub::info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pubAsub::info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pubAsub::info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pubAsub::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a71ec603c423d658e70d89e317c9473b";
  }

  static const char* value(const ::pubAsub::info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa71ec603c423d658ULL;
  static const uint64_t static_value2 = 0xe70d89e317c9473bULL;
};

template<class ContainerAllocator>
struct DataType< ::pubAsub::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pubAsub/info";
  }

  static const char* value(const ::pubAsub::info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pubAsub::info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 count\n"
"float32 information\n"
;
  }

  static const char* value(const ::pubAsub::info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pubAsub::info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.count);
      stream.next(m.information);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pubAsub::info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pubAsub::info_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "information: ";
    Printer<float>::stream(s, indent + "  ", v.information);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUBASUB_MESSAGE_INFO_H
