<robot name="camera" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- property -->
    <xacro:property name="camera_weight" value="0.01" />
    <xacro:property name="camera_length" value="0.02" />
    <xacro:property name="camera_width" value="0.05" />
    <xacro:property name="camera_height" value="0.05" />
    <xacro:property name="joint_camera_x" value="0.08" />
    <xacro:property name="joint_camera_y" value="0.0" />
    <xacro:property name="joint_camera_z" value="${base_length / 2 + camera_height / 2}" />

<!-- xacro2urdf -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="camera_color">
                <color rgba="0.5 0.5 0.5 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:Box_inertial_matrix m="${camera_weight}" l="${camera_length}" w="${camera_width}" h="${camera_height}" />
    </link>

    <gazebo reference="camera">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="camera2base" type="fixed">
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0.0 0.0 0.0" />
    </joint>

</robot>