<robot name="chassis" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- property -->
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="footprint_radius" value="0.001" />
    <xacro:property name="base_weight" value="2" />
    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="ground_distance" value="0.015" />
    <xacro:property name="joint_base2footprint_z" value="${base_length / 2 + ground_distance}" />
    <xacro:property name="wheel_weight" value="0.05" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="joint_wheel2base_z" value="${(joint_base2footprint_z - wheel_radius) * -1}" />
    <xacro:property name="spinwheel_weight" value="0.03" />
    <xacro:property name="spinwheel_radius" value="0.0075" />
    <xacro:property name="spinwheel_radius" value="0.0075" />
    <xacro:property name="joint_spinwheel2base_z" value="${(joint_base2footprint_z - spinwheel_radius) * -1}" />

<!-- macrofunc -->
    <xacro:macro name="wheel_func" params="wheel_name flag" >
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                    <!-- <cylinder radius="${}" length="${}" /> -->
                    <!-- <box size="${} ${} ${}" /> -->
                    <!-- <sphere radius="${}" /> -->
                    <!-- <mesh filename="package://simulation/meshes/autolabor_mini.stl" /> -->
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
                <material name="wheel_color">
                    <color rgba="0.0 0.0 0.0 0.5" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_weight}" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <gazebo reference="${wheel_name}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>    
        <joint name="${wheel_name}2base" type="continuous">
            <parent link="base_link"  />
            <child link="${wheel_name}_wheel" />
            <origin xyz="0.0 ${0.1 * flag} ${joint_wheel2base_z}" rpy="0.0 0.0 0.0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <xacro:macro name="spinwheel_func" params="spinwheel_name flag" >
        <link name="${spinwheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${spinwheel_radius}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <material name="wheel_color">
                    <color rgba="1.0 0.5 0.5 0.5" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${spinwheel_radius}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />   
            </collision>
            <xacro:sphere_inertial_matrix m="${spinwheel_weight}" r="${spinwheel_radius}" />
        </link>
        <gazebo reference="${spinwheel_name}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
        <joint name="${spinwheel_name}2base" type="continuous">
            <parent link="base_link" />
            <child link="${spinwheel_name}_wheel" />
            <origin xyz="${0.08 * flag} 0.0 ${joint_spinwheel2base_z}" rpy="0.0 0.0 0.0" />
            <axis xyz="1 1 1" />
        </joint>
    </xacro:macro>

<!-- xacro2urdf -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="base_color">
                <color rgba="1.0 0.5 0.5 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${base_weight}" r="${base_radius}" h="${base_length}" />
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <joint name="base2footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${joint_base2footprint_z}" rpy="0.0 0.0 0.0" />
        <axis xyz="0 0 0" />
    </joint>

    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <xacro:spinwheel_func spinwheel_name="front" flag="1" />
    <xacro:spinwheel_func spinwheel_name="back" flag="-1" />

</robot>


