// Generated by gencpp from file action/addintsResult.msg
// DO NOT EDIT!


#ifndef ACTION_MESSAGE_ADDINTSRESULT_H
#define ACTION_MESSAGE_ADDINTSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action
{
template <class ContainerAllocator>
struct addintsResult_
{
  typedef addintsResult_<ContainerAllocator> Type;

  addintsResult_()
    : sum(0)  {
    }
  addintsResult_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::action::addintsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action::addintsResult_<ContainerAllocator> const> ConstPtr;

}; // struct addintsResult_

typedef ::action::addintsResult_<std::allocator<void> > addintsResult;

typedef boost::shared_ptr< ::action::addintsResult > addintsResultPtr;
typedef boost::shared_ptr< ::action::addintsResult const> addintsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action::addintsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action::addintsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action::addintsResult_<ContainerAllocator1> & lhs, const ::action::addintsResult_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action::addintsResult_<ContainerAllocator1> & lhs, const ::action::addintsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action::addintsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action::addintsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action::addintsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action::addintsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action::addintsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action::addintsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action::addintsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::action::addintsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::action::addintsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action/addintsResult";
  }

  static const char* value(const ::action::addintsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action::addintsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 sum\n"
;
  }

  static const char* value(const ::action::addintsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action::addintsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addintsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action::addintsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action::addintsResult_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_MESSAGE_ADDINTSRESULT_H
